### ISSUE TITLE
Python-CheatSheets

### ISSUE THREAD

**Issue by CiroMeiraLins** [crescentpartha/CheatSheets-for-Developers#44]
It would be great if we had one file for python

**Comment by imran1509** [comment]
Hey I would like to work on this issue. Can you assign it to me?

**Comment by crescentpartha** [comment]
> If you want to work on this issue, then create a `python-cheatsheet.md` file inside the CheatSheets folder and give it a Tabular format like [git-cheatsheet.md](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/CheatSheets/git-cheatsheet.md) file.

1. Is it possible to create a cheat sheet for a programming language? 
2. What you will add to this cheat sheet? `Python programming learning resources` or `anything else`!

@CiroMeiraLins @imran1509

**Comment by imran1509** [comment]
okay assign this to me i will do it

**Comment by imran1509** [comment]
I can make it but it will be a very very long cheatsheet it will take hours to make
I will add everything in the cheatsheet.

So Can i make it?

**Comment by crescentpartha** [comment]
Please, follow the [contributing guidelines](https://github.com/crescentpartha/CheatSheets-for-Developers/blob/main/docs/CONTRIBUTING.md) before contributions. 

It will be better to `review your code` and `reduce the code conflict`, if you make a pull request with little changes (little section/chunk of code). You can create multiple pull requests as your wish.

Obviously, you can make it. You are most welcome!
My request is to create multiple pull requests to complete your desired cheatsheet so that I can quickly review your code and merge it.

Thanks, @imran1509

**Comment by imran1509** [comment]
Thanks
I have started the file and made first PR
Please review it and merge it so that i can keep writing
this will take around 2500 lines for the complete cheatsheet i think
so i will keep doing PRs on small intervals so that you can review regularly

**Comment by amanaggarwal06** [comment]
Hey, I want to work on this.
Can you please assign it to me @crescentpartha?

**Comment by amanaggarwal06** [comment]
Hey, please assign it to me.
I want to contribute.
